# Uncomment this line to define a global platform for your project
 platform :ios, '9.0'

target 'XWCNDict' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for XWCNDict
   pod 'ReactiveCocoa', '~> 4.0.4-alpha-4'
	
   pod 'FMDB', '~> 2.6'
end
